<?php
return [
    [
        'id'         => 'cloud-nine',
        'title'      => 'VIP Room 469 - Cloud Nine',
        'link'       => home_url('/khach-san-tinh-yeu/cloud-nine/'),
        'image'      => $theme_uri . '/assets/storage/qf/ci/qfcivbquyw6bbxs9vjeufbti5k4t_469-moonlit-love.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'karma',
        'title'      => 'Room 302 - Karma',
        'link'       => home_url('/khach-san-tinh-yeu/karma/'),
        'image'      => $theme_uri . '/assets/storage/e8/fo/e8fo0t2jei3ooib6yy7h4x2zigdc_302-karma.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'galaxy',
        'title'      => 'Room 202 - Galaxy',
        'link'       => home_url('/khach-san-tinh-yeu/galaxy/'),
        'image'      => $theme_uri . '/assets/storage/63/r7/63r7hvzdxw4kznzy14srvy4fkwdo_202-galaxy.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'flame',
        'title'      => 'Room 303 - Flame',
        'link'       => home_url('/khach-san-tinh-yeu/flame/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc61c48a15913d6bdc8229/Flame.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'honeymoon',
        'title'      => 'Room 301 - Honeymoon',
        'link'       => home_url('/khach-san-tinh-yeu/honeymoon/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc5f2d8a15913d6bdc81fe/honeymoon.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'lollipop',
        'title'      => 'Room 06 - Lollipop',
        'link'       => home_url('/khach-san-tinh-yeu/lollipop/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd2fa8a159118a146eb51/lollipop__4_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'after-sunset',
        'title'      => 'Room 04 - After Sunset',
        'link'       => home_url('/khach-san-tinh-yeu/after-sunset/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd0208a159118a146eb3b/after-sunset__1_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'blowj-up',
        'title'      => 'Room 08 - Blowj Up',
        'link'       => home_url('/khach-san-tinh-yeu/blowj-up/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd5d88a159118a146eb67/blowj-up__4_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'lalaland',
        'title'      => 'Room 09 - Lalaland',
        'link'       => home_url('/khach-san-tinh-yeu/lalaland/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd7168a159118a146eb71/lalaland__4_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'naive',
        'title'      => 'Room 201 - Naive',
        'link'       => home_url('/khach-san-tinh-yeu/naive/'),
        'image'      => $theme_uri . '/assets/uploads/images/606eb8a88a15917d2a0cdb34/naive1.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'bad-boy',
        'title'      => 'Room 02 - Bad Boy',
        'link'       => home_url('/khach-san-tinh-yeu/bad-boy/'),
        'image'      => $theme_uri . '/assets/uploads/images/600ac5388a159118a146eac9/bad-boy__2_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'hidden-frenzy',
        'title'      => 'Room 00 - Hidden Frenzy',
        'link'       => home_url('/khach-san-tinh-yeu/hidden-frenzy/'),
        'image'      => $theme_uri . '/assets/uploads/images/600ac2278a159118a146eab7/hidden-frenzy__2_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'passion',
        'title'      => 'Room 304 - Passion',
        'link'       => home_url('/khach-san-tinh-yeu/passion/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc62f18a15913d6bdc823d/Passion.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'bad-girl',
        'title'      => 'Room 001 - Bad girl',
        'link'       => home_url('/khach-san-tinh-yeu/bad-girl/'),
        'image'      => $theme_uri . '/assets/storage/do/4j/do4jgj8crqn9ct3kjme1flp1l9bj_001.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'master-n-slave',
        'title'      => 'Room 201 - Master n Slave',
        'link'       => home_url('/khach-san-tinh-yeu/master-n-slave/'),
        'image'      => $theme_uri . '/assets/storage/tp/c1/tpc1w7dl3b8d3jsn0997qcgcy9zt_201-master-n-slave.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'lolita',
        'title'      => 'Room 301 - Lolita',
        'link'       => home_url('/khach-san-tinh-yeu/lolita/'),
        'image'      => $theme_uri . '/assets/storage/wy/79/wy79insca4in9diukw7qq8zdes9l_301-lolita.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'amora',
        'title'      => 'Room 402 - Amora',
        'link'       => home_url('/khach-san-tinh-yeu/amora/'),
        'image'      => $theme_uri . '/assets/storage/1e/ak/1eakhk4fdk9spyiu1er2dch50zd7_402-amora.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'lover',
        'title'      => 'VIP 03 - Lover',
        'link'       => home_url('/khach-san-tinh-yeu/lover/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bce438a159118a146eb32/lover__4_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'on-top',
        'title'      => 'VIP 07 - On Top',
        'link'       => home_url('/khach-san-tinh-yeu/on-top/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd4b68a159118a146eb5b/on-top__8_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'get-high',
        'title'      => 'VIP 469 - Get High',
        'link'       => home_url('/khach-san-tinh-yeu/get-high/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc667a8a15913d6bdc8263/Get-High.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => '303-scarlet',
        'title'      => 'VIP Room 303 - Scarlet',
        'link'       => home_url('/khach-san-tinh-yeu/303-scarlet/'),
        'image'      => $theme_uri . '/assets/storage/4x/5q/4x5qwkkvxx3pz7350scsvbrt1j9x_303-scarlet.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'inferno',
        'title'      => 'VIP Room 102 - Inferno',
        'link'       => home_url('/khach-san-tinh-yeu/inferno/'),
        'image'      => $theme_uri . '/assets/storage/gf/yb/gfybu3xn4qupjynq9xq9t8p0gymy_102.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'whisper',
        'title'      => 'VIP 102 - Whisper',
        'link'       => home_url('/khach-san-tinh-yeu/whisper/'),
        'image'      => $theme_uri . '/assets/uploads/images/606eba398a15917d2a0cdb3c/whisper.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'wake-up',
        'title'      => 'VIP 101 - Wake up',
        'link'       => home_url('/khach-san-tinh-yeu/wake-up/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc49c18a15913d6bdc812b/wake-up.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'rhett-butler',
        'title'      => 'VIP 202 - Rhett Butler',
        'link'       => home_url('/khach-san-tinh-yeu/rhett-butler/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc57e78a15913d6bdc8195/rhett-butler.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'katana',
        'title'      => 'VIP Room 401 - Katana',
        'link'       => home_url('/khach-san-tinh-yeu/katana/'),
        'image'      => $theme_uri . '/assets/storage/q2/a6/q2a6jjsum90li8gzayh55emvp9uw_401-katana.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'kissing',
        'title'      => 'VIP 05 - Kissing',
        'link'       => home_url('/khach-san-tinh-yeu/kissing/'),
        'image'      => $theme_uri . '/assets/uploads/images/600bd1c98a159118a146eb45/kissing__3_.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'eden',
        'title'      => 'VIP Room 203 - Eden',
        'link'       => home_url('/khach-san-tinh-yeu/eden/'),
        'image'      => $theme_uri . '/assets/storage/6f/g3/6fg32jj8v1f0e9e4gl0ycu6rt38m_203-eden.jpg',
        'branchId'   => 'premium',
        'branchName' => '186 Hoàng Ngân',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'the-lust',
        'title'      => 'VIP 302 - The Lust',
        'link'       => home_url('/khach-san-tinh-yeu/the-lust/'),
        'image'      => $theme_uri . '/assets/uploads/images/60bc60638a15913d6bdc8216/the-lust.webp',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'VIP Suite',
    ],
    [
        'id'         => 'oasis',
        'title'      => 'VIP 01 - Oasis',
        'link'       => home_url('/khach-san-tinh-yeu/oasis/'),
        'image'      => $theme_uri . '/assets/uploads/images/600ac3df8a159118a146eac0/oasis.webp',
        'branchId'   => 'dang-tien-dong',
        'branchName' => '256B Đặng Tiến Đông',
        'badge'      => 'Deluxe',
    ],
    [
        'id'         => 'confession',
        'title'      => 'Confession',
        'link'       => home_url('/khach-san-tinh-yeu/confession/'),
        'image'      => 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1800&q=85',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Superior',
    ],
    [
        'id'         => 'hollywood',
        'title'      => 'Holywood',
        'link'       => home_url('/khach-san-tinh-yeu/hollywood/'),
        'image'      => 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1800&q=85',
        'branchId'   => 'phuc-la',
        'branchName' => '20 Phúc La Hà Đông',
        'badge'      => 'Superior',
    ],
];
